/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as publicMarketsIndexRouteImport } from './app/(public)/markets/index'
import { Route as publicPublicIndexRouteImport } from './app/(public)/_public/index'
import { Route as ApiAuthSplatRouteImport } from './app/api/auth/$'
import { Route as publicauthLoginIndexRouteImport } from './app/(public)/(auth)/login/index'

const publicMarketsIndexRoute = publicMarketsIndexRouteImport.update({
  id: '/(public)/markets/',
  path: '/markets/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicPublicIndexRoute = publicPublicIndexRouteImport.update({
  id: '/(public)/_public/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const publicauthLoginIndexRoute = publicauthLoginIndexRouteImport.update({
  id: '/(public)/(auth)/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/': typeof publicPublicIndexRoute
  '/markets': typeof publicMarketsIndexRoute
  '/login': typeof publicauthLoginIndexRoute
}
export interface FileRoutesByTo {
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/': typeof publicPublicIndexRoute
  '/markets': typeof publicMarketsIndexRoute
  '/login': typeof publicauthLoginIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(public)/_public/': typeof publicPublicIndexRoute
  '/(public)/markets/': typeof publicMarketsIndexRoute
  '/(public)/(auth)/login/': typeof publicauthLoginIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/api/auth/$' | '/' | '/markets' | '/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/api/auth/$' | '/' | '/markets' | '/login'
  id:
    | '__root__'
    | '/api/auth/$'
    | '/(public)/_public/'
    | '/(public)/markets/'
    | '/(public)/(auth)/login/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  publicPublicIndexRoute: typeof publicPublicIndexRoute
  publicMarketsIndexRoute: typeof publicMarketsIndexRoute
  publicauthLoginIndexRoute: typeof publicauthLoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)/markets/': {
      id: '/(public)/markets/'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof publicMarketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/_public/': {
      id: '/(public)/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicPublicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/(auth)/login/': {
      id: '/(public)/(auth)/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicauthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  publicPublicIndexRoute: publicPublicIndexRoute,
  publicMarketsIndexRoute: publicMarketsIndexRoute,
  publicauthLoginIndexRoute: publicauthLoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
