/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as publicDashboardRouteRouteImport } from './app/(public)/dashboard/route'
import { Route as publicPublicRouteRouteImport } from './app/(public)/_public/route'
import { Route as publicauthRouteRouteImport } from './app/(public)/(auth)/route'
import { Route as publicPublicIndexRouteImport } from './app/(public)/_public/index'
import { Route as ApiAuthSplatRouteImport } from './app/api/auth/$'
import { Route as publicDashboardHomeIndexRouteImport } from './app/(public)/dashboard/home/index'
import { Route as publicPublicSupportIndexRouteImport } from './app/(public)/_public/support/index'
import { Route as publicPublicMarketsIndexRouteImport } from './app/(public)/_public/markets/index'
import { Route as publicauthOnboardingIndexRouteImport } from './app/(public)/(auth)/onboarding/index'
import { Route as publicauthLoginIndexRouteImport } from './app/(public)/(auth)/login/index'

const publicDashboardRouteRoute = publicDashboardRouteRouteImport.update({
  id: '/(public)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const publicPublicRouteRoute = publicPublicRouteRouteImport.update({
  id: '/(public)/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const publicauthRouteRoute = publicauthRouteRouteImport.update({
  id: '/(public)/(auth)',
  path: '',
  getParentRoute: () => rootRouteImport,
} as any)
const publicPublicIndexRoute = publicPublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicPublicRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const publicDashboardHomeIndexRoute =
  publicDashboardHomeIndexRouteImport.update({
    id: '/home/',
    path: '/home/',
    getParentRoute: () => publicDashboardRouteRoute,
  } as any)
const publicPublicSupportIndexRoute =
  publicPublicSupportIndexRouteImport.update({
    id: '/support/',
    path: '/support/',
    getParentRoute: () => publicPublicRouteRoute,
  } as any)
const publicPublicMarketsIndexRoute =
  publicPublicMarketsIndexRouteImport.update({
    id: '/markets/',
    path: '/markets/',
    getParentRoute: () => publicPublicRouteRoute,
  } as any)
const publicauthOnboardingIndexRoute =
  publicauthOnboardingIndexRouteImport.update({
    id: '/onboarding/',
    path: '/onboarding/',
    getParentRoute: () => publicauthRouteRoute,
  } as any)
const publicauthLoginIndexRoute = publicauthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => publicauthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof publicDashboardRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/': typeof publicPublicIndexRoute
  '/login': typeof publicauthLoginIndexRoute
  '/onboarding': typeof publicauthOnboardingIndexRoute
  '/markets': typeof publicPublicMarketsIndexRoute
  '/support': typeof publicPublicSupportIndexRoute
  '/dashboard/home': typeof publicDashboardHomeIndexRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof publicDashboardRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/': typeof publicPublicIndexRoute
  '/login': typeof publicauthLoginIndexRoute
  '/onboarding': typeof publicauthOnboardingIndexRoute
  '/markets': typeof publicPublicMarketsIndexRoute
  '/support': typeof publicPublicSupportIndexRoute
  '/dashboard/home': typeof publicDashboardHomeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(public)/(auth)': typeof publicauthRouteRouteWithChildren
  '/(public)/_public': typeof publicPublicRouteRouteWithChildren
  '/(public)/dashboard': typeof publicDashboardRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(public)/_public/': typeof publicPublicIndexRoute
  '/(public)/(auth)/login/': typeof publicauthLoginIndexRoute
  '/(public)/(auth)/onboarding/': typeof publicauthOnboardingIndexRoute
  '/(public)/_public/markets/': typeof publicPublicMarketsIndexRoute
  '/(public)/_public/support/': typeof publicPublicSupportIndexRoute
  '/(public)/dashboard/home/': typeof publicDashboardHomeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/api/auth/$'
    | '/'
    | '/login'
    | '/onboarding'
    | '/markets'
    | '/support'
    | '/dashboard/home'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/api/auth/$'
    | '/'
    | '/login'
    | '/onboarding'
    | '/markets'
    | '/support'
    | '/dashboard/home'
  id:
    | '__root__'
    | '/(public)/(auth)'
    | '/(public)/_public'
    | '/(public)/dashboard'
    | '/api/auth/$'
    | '/(public)/_public/'
    | '/(public)/(auth)/login/'
    | '/(public)/(auth)/onboarding/'
    | '/(public)/_public/markets/'
    | '/(public)/_public/support/'
    | '/(public)/dashboard/home/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  publicauthRouteRoute: typeof publicauthRouteRouteWithChildren
  publicPublicRouteRoute: typeof publicPublicRouteRouteWithChildren
  publicDashboardRouteRoute: typeof publicDashboardRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)/dashboard': {
      id: '/(public)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof publicDashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/_public': {
      id: '/(public)/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicPublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/(auth)': {
      id: '/(public)/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicauthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/_public/': {
      id: '/(public)/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicPublicIndexRouteImport
      parentRoute: typeof publicPublicRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/dashboard/home/': {
      id: '/(public)/dashboard/home/'
      path: '/home'
      fullPath: '/dashboard/home'
      preLoaderRoute: typeof publicDashboardHomeIndexRouteImport
      parentRoute: typeof publicDashboardRouteRoute
    }
    '/(public)/_public/support/': {
      id: '/(public)/_public/support/'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof publicPublicSupportIndexRouteImport
      parentRoute: typeof publicPublicRouteRoute
    }
    '/(public)/_public/markets/': {
      id: '/(public)/_public/markets/'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof publicPublicMarketsIndexRouteImport
      parentRoute: typeof publicPublicRouteRoute
    }
    '/(public)/(auth)/onboarding/': {
      id: '/(public)/(auth)/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof publicauthOnboardingIndexRouteImport
      parentRoute: typeof publicauthRouteRoute
    }
    '/(public)/(auth)/login/': {
      id: '/(public)/(auth)/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicauthLoginIndexRouteImport
      parentRoute: typeof publicauthRouteRoute
    }
  }
}

interface publicauthRouteRouteChildren {
  publicauthLoginIndexRoute: typeof publicauthLoginIndexRoute
  publicauthOnboardingIndexRoute: typeof publicauthOnboardingIndexRoute
}

const publicauthRouteRouteChildren: publicauthRouteRouteChildren = {
  publicauthLoginIndexRoute: publicauthLoginIndexRoute,
  publicauthOnboardingIndexRoute: publicauthOnboardingIndexRoute,
}

const publicauthRouteRouteWithChildren = publicauthRouteRoute._addFileChildren(
  publicauthRouteRouteChildren,
)

interface publicPublicRouteRouteChildren {
  publicPublicIndexRoute: typeof publicPublicIndexRoute
  publicPublicMarketsIndexRoute: typeof publicPublicMarketsIndexRoute
  publicPublicSupportIndexRoute: typeof publicPublicSupportIndexRoute
}

const publicPublicRouteRouteChildren: publicPublicRouteRouteChildren = {
  publicPublicIndexRoute: publicPublicIndexRoute,
  publicPublicMarketsIndexRoute: publicPublicMarketsIndexRoute,
  publicPublicSupportIndexRoute: publicPublicSupportIndexRoute,
}

const publicPublicRouteRouteWithChildren =
  publicPublicRouteRoute._addFileChildren(publicPublicRouteRouteChildren)

interface publicDashboardRouteRouteChildren {
  publicDashboardHomeIndexRoute: typeof publicDashboardHomeIndexRoute
}

const publicDashboardRouteRouteChildren: publicDashboardRouteRouteChildren = {
  publicDashboardHomeIndexRoute: publicDashboardHomeIndexRoute,
}

const publicDashboardRouteRouteWithChildren =
  publicDashboardRouteRoute._addFileChildren(publicDashboardRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  publicauthRouteRoute: publicauthRouteRouteWithChildren,
  publicPublicRouteRoute: publicPublicRouteRouteWithChildren,
  publicDashboardRouteRoute: publicDashboardRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
